version: '3.6'
services:
  nginx:
    container_name: nginx
    image: nginx:1-alpine
    ports:
      - 9090:80
    volumes:
      - public:/usr/share/nginx/html

volumes:
  public:
    external: true
    name: docker-nfs_example_public
